--1. 영어영문학과 (학과코드 002) 학생들 학번,이름,입학년도 빠른 순으로 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 학번 ASC, 이름 ASC, 입학년도 ASC;

--2. 교수중 이름이 한글자가 아닌 교수 이름과 주민번호 출력 
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) != '3';

--쌤답안
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


--3. 남자 교수들 이름과 나이 출력 적은-> 많은 순서, 나이는 만으로 계산
SELECT PROFESSOR_NAME 교수이름,
       TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD'))/12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY PROFESSOR_SSN DESC; 

-- 쌤답안 
SELECT PROFESSOR_NAME "교수이름", 
       TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 2),'YYYY'))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;


--SELECT TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE('19920929','YYYYMMDD'))/12)
--FROM DUAL; 

--4. 교수들 성 없이 출력하기
SELECT SUBSTR(PROFESSOR_NAME,2,3) 이름
FROM TB_PROFESSOR;

--5. 재수생 입학자 구하기, 19살 입학 재수생X
SELECT STUDENT_NO, STUDENT_NAME,
      MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'))/12
FROM TB_STUDENT
WHERE MONTHS_BETWEEN(ENTRANCE_DATE ,TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'))/12>19 AND
      MONTHS_BETWEEN(ENTRANCE_DATE ,TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'))/12<=20;

--6. 2020 크리스마스 무슨요일 
SELECT TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DAY')"2020 크리스마스"
FROM DUAL;

--7. T0_DATE('99/10/11','YY/MM/DD'), ('49/10/11' YY/MM/DD),  T0_DATE('99/10/11','RR/MM/DD'), ('49/10/11' RR/MM/DD) 
SELECT TO_CHAR(TO_DATE('991011','YYMMDD'),'YYYY"년" MM"월" DD"일"')
FROM DUAL; 

SELECT TO_CHAR(TO_DATE('491011','YYMMDD'),'YYYY"년" MM"월" DD"일"')
FROM DUAL; 

SELECT TO_CHAR(TO_DATE('991011','RRMMDD'),'YYYY"년" MM"월" DD"일"')
FROM DUAL; 

SELECT TO_CHAR(TO_DATE('491011','RRMMDD'),'YYYY"년" MM"월" DD"일"')
FROM DUAL; 

--8. 2000년도 이후 입학자들 A로 시작함 2000년도 이전 학번 받은 학생들 학번, 이름 출력
SELECT STUDENT_NO 학번, STUDENT_NAME 이름
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

--9. 학번 A517178 한아름 학생의 학점 총 평점, 반올림 소수점 이하
SELECT ROUND(AVG(POINT),1) AS 평정
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

SELECT STUDENT_NAME, STUDENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME = '한아름';

--10. 학과별 학생수를 구하여 "학과번호", "학생수(명)" 의 형태로 해더를 만들어 결과값이 출력되도록
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1; 

--11. 지도 교수를 배정받지 못핫 학생의 수는 몇명 정도 되는지 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12 학번 A112113인 김고운 학생의 년도 별 평점을 
SELECT SUBSTR(TERM_NO,1,4) AS 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13.학과 별 휴학생 수를 파악하고자 한다. 학과 번호와 휴학생 수를 표시하는 출력 
SELECT DEPARTMENT_NO 학과코드, COUNT(DECODE(ABSENCE_YN,'Y',1)) 휴학생
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1; 

--14. 동명이인 학생들 이름을 찾기 
SELECT DISTINCT STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1; 

--15. 학번 A112113인 김고운 학생의 년도 학기 별 평점 누적 평점
SELECT SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,6), ROUND(AVG(POINT),1) 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,6))
ORDER BY 1;

