--1. 춘 기술대학 학과 이름과 계열 표시하기
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT;

--2. 학과의 학과 정원 정리
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

--3. 국어국문학과 휴학중인 여학생 찾기 
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND SUBSTR(STUDENT_SSN,8,1) = '2';

--4. 도서 장기 연체자 찾기 A513079, A513090, A513091, A513110, A513119
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NO DESC; 

--5. 입학정원이 20명 이상 30명 이하인 학과들의 학과 이름과 계열 출력
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY
BETWEEN 20 AND 30; 

--6. 총장 이름 찾기
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL; 

--7.학과가 지정되어 있지 않는 학생
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8. 선수과목이 존재하는 과목들이 어떤것인지 과목번호로 조해
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL; 

--9. 춘대학 어떤 계열들이 있는지 
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--10. 02학번 전주 거주자들의 모임을 만들려고 한다. 휴학한 사람들은 제외한 재학중인 학생들의 학번, 이름, 주민번호
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE BETWEEN '02/01/01' AND '02/12/31' AND ABSENCE_YN = 'N' AND SUBSTR(STUDENT_ADDRESS,1,2) = '전주';










