--1. 학생이름과 주소지를 표시 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT;

--2. 휴학중인 학생 이름, 주민번호 나이가 적은 순서
SELECT STUDENT_NAME 이름, STUDENT_SSN 주민번호
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,2) ASC; 

--3. 주소지 강원도, 경기도인 학생 중 1900년대 학번을 가진 학생들 이름과 학번 오름차순
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND STUDENT_ADDRESS LIKE '경기도%'
ORDER BY 1;

--4.현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인 할 수 있는 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
  FROM TB_PROFESSOR P, TB_DEPARTMENT D
 WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '법학과'
 ORDER BY SUBSTR(PROFESSOR_SSN,1,2) ASC; 
 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
  FROM TB_PROFESSOR 
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과'
 ORDER BY SUBSTR(PROFESSOR_SSN,1,2) ASC;
 
--5. 2004년 2학기에 'C3118100' 수강한 학생들 학점 조회. 학점이 높은 학생부터 "학점이 같으면 학번이 낮은 학생부터**"
SELECT STUDENT_NO, POINT
  FROM TB_GRADE
 WHERE SUBSTR(TERM_NO,1,4) = '2004'
   AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC; 

--6.  학생번호, 학생이름, 학과 이름. 학생 이름으로 오름차순 정렬하여 출력
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
  FROM TB_STUDENT S, TB_DEPARTMENT D
 WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
 ORDER BY 1 DESC;
 
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
  FROM TB_STUDENT 
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
 ORDER BY 1 DESC; 
 
 --7. 춘 기술대학교의 과목 이름과 과목의 학과 이름을 출력
SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS C, TB_DEPARTMENT D
 WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO;

SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS 
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);
  
--8.과목별 교수 이름 
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS C, TB_PROFESSOR P
 WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO;
 
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS 
  JOIN TB_PROFESSOR USING(DEPARTMENT_NO);
  
--9. 8번의 결과 중 '인문사회' 계열에 속학 과목의 교수 이름 찾으려고 한다. 
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS C, TB_PROFESSOR P, TB_DEPARTMENT D
 WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO
   AND P.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND CATEGORY = '인문사회';

SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS 
  JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
 WHERE CATEGORY = '인문사회';

--10. '음악학과' 평점 학번 이름 전체 평점
SELECT S.STUDENT_NO 학번, S.STUDENT_NAME 이름, POINT 평점
  FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
 WHERE S.STUDENT_NO = G.STUDENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND D.DEPARTMENT_NAME LIKE '음악%'
 ORDER BY 1;  -- ***** 다시 풀어보기
 
 --11. A313047 , 학과이름, 이름, 지도교수
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수
  FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
 WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND D.DEPARTMENT_NO = P.DEPARTMENT_NO
   AND STUDENT_NO = 'A313047';
   
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수
  FROM TB_STUDENT 
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
  JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
 WHERE STUDENT_NO='A313047';
 
--12. 2007년도 '인간관계론'과목 수강한 이름 TERM_NAME
SELECT STUDENT_NAME, TERM_NO
  FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
 WHERE S.STUDENT_NO = G.STUDENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND SUBSTR(TERM_NO,1,4) = '2007';

SELECT DEPARTMENT_NAME 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
 AND STUDENT_NO = 'A511081';
WHERE STUDENT_NAME = '김혜원'; ---> 교육학과

--13. 예체능 과목 담당교수 배정받지 못한 과목을 찾아 그과목 이름과 학과 이름을 
SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS C, TB_DEPARTMENT D, TB_CLASS_PROFESSOR P
 WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND C.CLASS_NO = P.CLASS_NO
   AND D.CATEGORY = '예체능';
  -- AND CLASS_NO <> PROFESSOR_NO; *************** 다시보기
  
--14. 서반아어 학과 
SELECT STUDENT_NAME, PROFESSOR_NAME
  FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
 WHERE S.DEPARTMENT_NO = P.DEPARTMENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '서반아어학과'; --- 다른과목으로 하면 됨. 사반만 안됨. 

SELECT DEPARTMENT_NAME 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
 AND STUDENT_NO = 'A111232';
 
SELECT STUDENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME = '주하나';

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '001';
   
--15. 휴학생 아닌 학생 평점 4.0 이상인 학생 학번, 이름, 학과이름, 평점
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, POINT
  FROM TB_STUDENT S, TB_DEPARTMENT D, TB_GRADE G
 WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND S.STUDENT_NO = G.STUDENT_NO
   AND POINT >= 4.0;
   
   