--1. 테이블 이름 TB_CATEGORY, 컬럼 NAME, USE_YN
CREATE TABLE TB_CATEGORY (
NAME VARCHAR2(10),
USE_YN CHAR(1) DEFAULT 'Y'
);

--2. 테이블 이름 TB_CLASS_TYPE 컬럼  NO, NAME
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5)PRIMARY KEY,
NAME VARCHAR2(10)
);

--3. TB_CATEGORY NAME 컬럼에 PK 생성
ALTER TABLE TB_CATEGORY ADD CONSTRAINT NAME_PK PRIMARY KEY(NAME);

--4. TB_CLASS_TYPE  NAME에 NULL 값이 들어가지 않도록
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL; 

--5. NO -> 10 NAME ->20인 사이즈로 변경 타입은 그대로
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR(20);

--6. NO, NAME 앞에 CATEGORY_ 붙이기 
ALTER TABLE TB_CATEGORY RENAME COLUMN TB_NAME TO CATEGORY_NAME; 
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN TB_NO TO CATEGORY_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN TB_NAME TO CATEGORY_NAME;

--7. TB_CATEGORY , TB_CLASS_TYPE PRIMARY KEY이름을 PK_ 로 변경 
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT NAME_PK TO PK_CATEGORY_NAME;
ALTER TABLE TB_cLASS_TYPE RENAME CONSTRAINT SYS_C007194 TO PK_CLT_NO;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007196 TO PK_CLT_NAME; 

--8. 
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학',DEFAULT);
INSERT INTO TB_CATEGORY VALUES('의학',DEFAULT);
INSERT INTO TB_CATEGORY VALUES('예체능',DEFAULT);
INSERT INTO TB_CATEGORY VALUES('인문사회',DEFAULT);
COMMIT;

--9. 
ALTER TABLE TB_DEPARTMENT 
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY 
FOREIGN KEY(CATEGORY) 
REFERENCES TB_CATEGORY(CATEGORY_NAME);

--10. 학생일반정보 VIEW를 만들자 
CREATE OR REPLACE VIEW VW_STUD_INFO
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT; 
     
--11. ** 단,VIEW는 단순 SELECT 만을 할 경우 학과별로 정렬되어 화면에 보여지게 만드시오 ???
CREATE OR REPLACE VIEW VW_COACH
AS SELECT STUDENT_NAME, DEPARTMENT_NAME,PROFESSOR_NAME
     FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
    WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
      AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+)
      ORDER BY 2;
      
SELECT* FROM VW_COACH;

--12. 모든 학과의 학과별 학생 수를 확인할 수 있도록 VIEW를 작성
CREATE OR REPLACE VIEW VW_DEP_STU_CNT
AS SELECT DEPARTMENT_NAME, COUNT(*)STUDENT_COUNT
     FROM TB_DEPARTMENT D, TB_STUDENT S
    WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO
 GROUP BY DEPARTMENT_NAME;

--13. 
UPDATE VW_STUD_INFO
   SET STUDENT_NAME = '황학천'
 WHERE STUDENT_NO = 'A213046';

SELECT STUDENT_NAME
FROM VW_STUD_INFO
WHERE STUDENT_NO = 'A213046';

--14.
CREATE OR REPLACE VIEW VW_STUD_INFO
AS SELECT * 
FROM TB_STUD_INFO
WITH READ ONLY; 
    
--15. 과목 최대 3개 
SELECT CLASS_NO 과목번호, MAX(CAPACITY)
FROM TB_CLASS C,TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
HAVING 
GROUP BY CLASS_NO;


SELECT MAX(CAPACITY)
FROM TB_DEPARTMENT
GROUP BY DEPARTMENT_NO
ORDER BY 1 DESC;


