--1. TB_CLASS_TYPE에 입력
INSERT INTO TB_CLASS_TYPE VALUES(01,'전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02,'전공성택');

DELETE FROM TB_CLASS_TYPE
WHERE CATEGORY_NAME = '전공성택';

INSERT INTO TB_CLASS_TYPE VALUES(02,'전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03,'교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04,'교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05,'논문지도');

--2. 서브쿼리를 이용하시요???? --> GOT IT!
CREATE TABLE TB_STU_INFO (
STUDENT_NO VARCHAR2(10),
STUDENT_NAME VARCHAR2(40),
STUDENT_ADDRESS VARCHAR2(200)
);

DROP TABLE TB_STU_INFO;

CREATE TABLE TB_STUD_INFO
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT;
     
--3. 국어국문학과 학생들의 정보 가져오기 
CREATE TABLE TB_KOR_CL
AS SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'),'YYYYMMDD')출생년도, PROFESSOR_NAME
     FROM TB_STUDENT S, TB_PROFESSOR P 
    WHERE S.COACH_PROFESSOR_NO = P.PROFESSOR_NO;

--4. 현 학과 정원 10% 증가, 반올리 사용 
SELECT ROUND(CAPACITY * 1.1) "정원10% 증가"
  FROM TB_DEPARTMENT; 
  
--5. A413042 박건우 학생 주소 변경 서울시 종로구 숭인동 181-21
UPDATE TB_STUDENT
   SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
 WHERE STUDENT_NAME = '박건우';
 
SELECT STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NAME LIKE '박건%';

--6. 주민번호 보호법 뒷번호 없애기
UPDATE TB_STUDENT
   SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

SELECT * FROM TB_STUDENT;   

COMMIT;
--7. 김명훈 학셍 2005년 1학기 피부생리학 점수 정정 3.5로 변경
UPDATE TB_GRADE
   SET POINT = 3.5
 WHERE CLASS_NO IN (SELECT STUDENT_NO
                     FROM TB_STUDENT S, TB_GRADE G, TB_CLASS C
                    WHERE S.STUDENT_NO = G.STUDENT_NO
                      AND G.CLASS_NO = C.CLASS_NO
                      AND SUBSTR(TERM_NO,1,6) = '200501'
                      AND CLASS_NAME = '피부생리학'
                      AND STUDENT_NAME = '김명훈');
                      
SELECT POINT
FROM TB_STUDENT S, TB_GRADE G, TB_CLASS C
WHERE S.STUDENT_NO = G.STUDENT_NO
  AND S.DEPARTMENT_NO = C.DEPARTMENT_NO
  AND SUBSTR(TERM_NO,1,6) = '200501'
  AND CLASS_NAME = '피부생리학';
  --AND STUDENT_NAME = '김명훈';


--8. TB_GRADE 휴학생 성적항목 제거
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                       FROM TB_STUDENT
                      WHERE ABSENCE_YN = 'Y');

SELECT DISTINCT STUDENT_NAME
FROM TB_STUDENT S, TB_GRADE G
WHERE S.STUDENT_NO = G.STUDENT_NO
 AND ABSENCE_YN ='Y';






     